### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by 17Reset** [MikePopoloski/pyslang#115]
Why can't I build pyslang successfully?

**Comment by MikePopoloski** [comment]
I don't know, why can't you?

**Comment by 17Reset** [comment]
> I don't know, why can't you?

Tips like this：Building wheel for pyslang (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for pyslang (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [138 lines of output]
fatal: not a git repository (or any of the parent directories): .git
WARNING: '' not a valid package name; please use only .-separated package names in setup.py

**Comment by MikePopoloski** [comment]
You need to give more information if you want help. What commands exactly did you run? What is the full output of running those commands?

**Comment by 17Reset** [comment]
> You need to give more information if you want help. What commands exactly did you run? What is the full output of running those commands?
Sorry, the problem I encountered is as follows:
D:\App\Python\Scripts>pip install pyslang
Collecting pyslang
  Using cached pyslang-3.0.0.tar.gz (945 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyslang
  Building wheel for pyslang (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyslang (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [129 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      WARNING: '' not a valid package name; please use only .-separated package names in setup.py
      C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is MSVC 19.35.32217.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: D:/App/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.35.32217.1
      CMake Warning (dev) at C:/Users/zhujiang/AppData/Local/Temp/pip-build-env-ilxzfons/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:168 (if):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at C:/Users/zhujiang/AppData/Local/Temp/pip-build-env-ilxzfons/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:189 (elseif):
        Policy CMP0054 is not set: Only interpret if() arguments as variables or
        keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
        details.  Use the cmake_policy command to set the policy and suppress this
        warning.

        Quoted variables like "MSVC" will no longer be dereferenced when the policy
        is set to NEW.  Since the policy is not set the OLD behavior will be used.
      Call Stack (most recent call first):
        CMakeLists.txt:4 (ENABLE_LANGUAGE)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: D:/App/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (4.6s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/AppData/Local/Temp/pip-install-k9d462z2/pyslang_d82763474bf744e5a58005a04ebefdbd/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\_skbuild\win-amd64-3.11\cmake-build
        Command:
          'C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\slang' -G Ninja --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\_skbuild\win-amd64-3.11\cmake-install\slang' -DPYTHON_VERSION_STRING:STRING=3.11.1 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\App\Python\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\App\Python\Include' '-DPYTHON_LIBRARY:PATH=D:\App\Python\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\App\Python\python.exe' '-DPython_ROOT_DIR:PATH=D:\App\Python' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\App\Python\Include' '-DPython_LIBRARY:PATH=D:\App\Python\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\App\Python\python.exe' '-DPython3_ROOT_DIR:PATH=D:\App\Python' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\App\Python\Include' '-DPython3_LIBRARY:PATH=D:\App\Python\libs\python311.lib' -DSLANG_INCLUDE_TESTS=OFF -DSLANG_INCLUDE_TOOLS=OFF -DSLANG_INCLUDE_PYLIB=ON -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- CMake version: 3.26.3
      -- slang version: 3.0.0+0
      -- The CXX compiler identification is MSVC 19.35.32217.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: D:/App/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx86/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Python: D:/App/Python/python.exe (found version "3.11.1") found components: Interpreter Development.Module
      -- Build STATIC library as: svlang
      -- Module support is disabled.
      -- Version: 9.1.0
      -- Build type: Release
      -- CXX_STANDARD: 17
      -- Required features: cxx_variadic_templates
      -- Using remote fmt library
      ninja: error: Stat(C:/Users/AppData/Local/Temp/pip-install-k9d462z2/pyslang_d82763474bf744e5a58005a04ebefdbd/_skbuild/win-amd64-3.11/cmake-build/_deps/unordered_dense-subbuild/unordered_dense-populate-prefix/src/unordered_dense-populate-stamp/unordered_dense-populate-done): Filename longer than 260 characters

      CMake Error at C:/Users/AppData/Local/Temp/pip-build-env-ilxzfons/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1622 (message):
        Build step for unordered_dense failed: 1
      Call Stack (most recent call first):
        C:/Users/zhujiang/AppData/Local/Temp/pip-build-env-ilxzfons/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1762:EVAL:2 (__FetchContent_directPopulate)
        C:/Users/zhujiang/AppData/Local/Temp/pip-build-env-ilxzfons/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1762 (cmake_language)
        C:/Users/zhujiang/AppData/Local/Temp/pip-build-env-ilxzfons/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1976 (FetchContent_Populate)
        external/CMakeLists.txt:51 (FetchContent_MakeAvailable)
        CMakeLists.txt:214 (include)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\skbuild\cmaker.py", line 356, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\slang' -G Ninja --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\_skbuild\win-amd64-3.11\cmake-install\slang' -DPYTHON_VERSION_STRING:STRING=3.11.1 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\AppData\Local\Temp\pip-build-env-ilxzfons\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=D:\App\Python\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=D:\App\Python\Include' '-DPYTHON_LIBRARY:PATH=D:\App\Python\libs\python311.lib' '-DPython_EXECUTABLE:PATH=D:\App\Python\python.exe' '-DPython_ROOT_DIR:PATH=D:\App\Python' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=D:\App\Python\Include' '-DPython_LIBRARY:PATH=D:\App\Python\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=D:\App\Python\python.exe' '-DPython3_ROOT_DIR:PATH=D:\App\Python' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=D:\App\Python\Include' '-DPython3_LIBRARY:PATH=D:\App\Python\libs\python311.lib' -DSLANG_INCLUDE_TESTS=OFF -DSLANG_INCLUDE_TOOLS=OFF -DSLANG_INCLUDE_PYLIB=ON -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\slang
        Working directory:
          C:\Users\AppData\Local\Temp\pip-install-k9d462z2\pyslang_d82763474bf744e5a58005a04ebefdbd\_skbuild\win-amd64-3.11\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyslang
Failed to build pyslang
ERROR: Could not build wheels for pyslang, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\App\Python\Scripts\pip.exe\__main__.py", line 7, in <module>
  File "D:\App\Python\Lib\site-packages\pip\_internal\cli\main.py", line 79, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\pip\_internal\cli\base_command.py", line 100, in main
    with self.main_context():
  File "D:\App\Python\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "D:\App\Python\Lib\site-packages\pip\_internal\cli\command_context.py", line 19, in main_context
    with self._main_context:
  File "D:\App\Python\Lib\contextlib.py", line 586, in __exit__
    raise exc_details[1]
  File "D:\App\Python\Lib\contextlib.py", line 571, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "D:\App\Python\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 31, in global_tempdir_manager
    with ExitStack() as stack:
  File "D:\App\Python\Lib\contextlib.py", line 586, in __exit__
    raise exc_details[1]
  File "D:\App\Python\Lib\contextlib.py", line 571, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 156, in __exit__
    self.cleanup()
  File "D:\App\Python\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "D:\App\Python\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\App\Python\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "D:\App\Python\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\App\Python\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\App\Python\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\App\Python\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 6 more times]
  File "D:\App\Python\Lib\shutil.py", line 626, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\App\Python\Lib\shutil.py", line 624, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] 目录不是空的。: 'C:\\Users\\\AppData\\Local\\Temp\\pip-install-k9d462z2\\pyslang_d82763474bf744e5a58005a04ebefdbd\\_skbuild\\win-amd64-3.11\\cmake-build\\_deps\\unordered_dense-subbuild\\unordered_dense-populate-prefix\\src\\unordered_dense-populate-stamp'

D:\App\Python\Scripts>

**Comment by 17Reset** [comment]
> These commands all succeed for me when I run them. Do you have a special setup for git? It seems like there's some problem with your environment or your git installation that is preventing it from working correctly.

When I run: git clone https://github.com/MikePopoloski/pyslang.git, no problem at all.
But run: git submodule update - init -- recursive, don't seem to anything from https://github.com/MikePopoloski/slang.git.

**Comment by 17Reset** [comment]
I still hope to know why those errors occur when using pip insatall pyslang. Thank you very much indeed

**Comment by 17Reset** [comment]
> It seems like the same problem, some git operation fails during the build of the pyslang wheel. Your environment must unique and/or messed up in some way. Typically pip install doesn't require you to build a binary at all because the package has binaries for common systems already included, so you must be using an uncommon system.

What is an uncommon system?

**Comment by MikePopoloski** [comment]
You can see the list of prebuilt binaries here: https://pypi.org/project/pyslang/#files

**Comment by 17Reset** [comment]
> 您可以在此处查看预构建二进制文件的列表：https://pypi.org/project/pyslang/#files

Is python3.11 not supported?

**Comment by 17Reset** [comment]
I see what's going on. Is it the wrong version of python, pyslang doesn't support python311

**Comment by MikePopoloski** [comment]
I haven't tried to build it for py3.11 yet but I would be surprised if that was the cause of the build failure, it seems unrelated. Not having py3.11 prebuilt binaries in PyPi though is why you are having to build locally in the first place.
